import { Child, RoutineTask, RewardItem, NotificationItem, PointTransaction } from './types';

export const INITIAL_CHILDREN: Child[] = [
  {
    id: 'lucas',
    name: 'Lucas',
    age: '10 anos',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBHdKP6H-f_NoNM5Wb02ayhgzmSFIxH6JcMraJTXvpW9b1fQg94vNYDStX0Lv_gRv5BRejMlpxttswM5drulkRRCYt8cUckk6UCna3YsW_9z7YqCh8_sSbnhcFuRVyD5Vz_wUVQ5IJIYnk1h1G93lSukdzrQQhkuQvLzCMuJLNGrPuURtyEN_e5HqZjCSqxnVz0u1vZeSmBK3ZX2I1AKjmg-k_KiquY5mFZE1JfYOLIJmLD6jDxZL6C',
    level: 'Nível 4',
    weekPercent: 92,
    balance: 480,
    accumulated: 1250,
    spent: 770,
    badgeNumber: '10',
    streakDays: 14,
  },
  {
    id: 'beatriz',
    name: 'Beatriz',
    age: '7 anos',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA9BF-FaAi1aCNTKdW5vsD-zwurBgIV-MFh9Ba5XqyhZ6TiZYeBls-O9KtMnlq0gcWARGkg7XWoqwV6ZgJeWkjlLf-M2pTBvKsm9kwkmghdPktXljND1SHMnlfJj3cXzrIxQPuDABEFVWTX98cQ07C-bza1O21REgyLg8bP56P_4MP_dt59K2BwZERY3N_S8PxPgNQ9ojLUgwZtkOqlEk8y4CwtUSvcz8U6YxLcRK0P6WKIgluytUA1',
    level: 'Estrela ⭐',
    weekPercent: 96,
    balance: 620,
    accumulated: 980,
    spent: 360,
    badgeNumber: '7',
    badgeLabel: 'Estrela ⭐',
    streakDays: 19,
  },
];

export const INITIAL_TASKS: RoutineTask[] = [
  {
    id: 'card-reg-1082',
    code: '#REG-1082',
    tarCode: 'TAR-001',
    title: 'Arrumar a cama e organizar o quarto',
    category: 'Organização',
    childId: 'lucas',
    childName: 'Lucas',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAtHDj_fZ4F1-SYxJp2YTb2SiQFXqzcO2IDSmTcV7xE1tFYlYR1lMFIWiXEhWRJ2PYA6SM4R1gNUcESOkjs-beJr6FhRFPtBDbuOI76eLSeV1Vzc7u9AYb78Gn6cpcihbknAHu1f1Tp3Iabp_vPmdiVVWdekArlQsvtXlWX24faQWOV1LGoQDMusiXS_WFroP9yBXZxjVRCaAc2FJygA6ysK3daGqDHhWEYDozPuCNQOOX0JE_3vada',
    points: 50,
    basePoints: 50,
    status: 'todo',
    onTime: true,
    timingLabel: 'Prazo até às 20:00',
    criteria: 'A cama deve estar esticada, sem brinquedos no chão e armário fechado.',
    limitTime: '20:00',
    completedAt: '',
    duration: '15 min previstos',
    feedback: 'Aguardando execução pela criança.',
    hasPenalty: false,
    penaltyAmount: 0,
    proofPhotoUrl: 'https://picsum.photos/seed/quarto_organizado/800/600',
  },
  {
    id: 'card-reg-1083',
    code: '#REG-1083',
    tarCode: 'TAR-004',
    title: 'Lição de casa de Matemática',
    category: 'Estudos',
    childId: 'lucas',
    childName: 'Lucas',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCSd_mCBoarbq4n4bVAxQwYNzMs7asEIuBcQFh-NRQtkECZE7ccQAqKCK0F2XgkgwLVvu07FtcvQ3tJI1uV-ZwWG1FQajzOuSX7QuPnP0N79Q7a4NSLl3Vd5Z37a5q2-_qyCkustc-3BxvZh6-4nzxtVDNhkFVsIHcO7OdDLQRiUzwBSAEpWekAMkmnakXhyfdMTmrJj1FRLWPySiwWHThxmc0Q8CI95JRjU6cpLOJQdsCb5WUSRgZ9',
    points: 70,
    basePoints: 80,
    status: 'pending',
    onTime: false,
    timingLabel: 'Atrasado em 25 minutos',
    criteria: 'Caderno completo, exercícios da pág. 42 a 45 resolvidos a lápis com memória de cálculo.',
    limitTime: '18:30',
    completedAt: '18:55',
    duration: '50 min (prev. 45 min)',
    feedback: 'Excelente resolução dos exercícios, mas atente-se ao horário limite!',
    hasPenalty: true,
    penaltyAmount: 10,
    proofPhotoUrl: 'https://picsum.photos/seed/math_homework/800/600',
  },
  {
    id: 'card-reg-1084',
    code: '#REG-1084',
    tarCode: 'TAR-002',
    title: 'Escovar os dentes e lavar o rosto',
    category: 'Higiene',
    childId: 'beatriz',
    childName: 'Beatriz',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBr_VVf0bQ-j3mZP5XUyrSDq1rSiBy4rV-g_rw66wtT0lgdHIiAx4VLl_s974LtG3LQc_uTcwuHMiiYzn4mB52Apqm9fZ4D4i_ABQWUODIN5y5KdC3XDrniW-yiW8MiIV5doBN1x2bCf-8UePB4i_R2ukZMyLU5CUUNMXP9yhtantgM_gYOIzaj7mZ4PVoxgmWsLeoxXUcQZcbJuzVEhhnYcAjrRycV-W2A9mzNikjtlWE_7OvkZdtW',
    points: 30,
    basePoints: 30,
    status: 'todo',
    onTime: true,
    timingLabel: 'Prazo noturno: 21:00',
    criteria: 'Escovação por 2 minutos, uso de fio dental e enxágue facial.',
    limitTime: '21:00',
    completedAt: '',
    duration: '6 min',
    feedback: 'Rotina diária noturna habitual',
    hasPenalty: false,
    penaltyAmount: 0,
    proofPhotoUrl: 'https://picsum.photos/seed/brush_teeth/800/600',
  },
  {
    id: 'card-reg-1085',
    code: '#REG-1085',
    tarCode: 'TAR-007',
    title: 'Organizar mochila para amanhã',
    category: 'Organização',
    childId: 'beatriz',
    childName: 'Beatriz',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAUtf05fCv6wFbX0I5KeTZySQRXAknH_9AdPlyBcR7RqvqHn31XZRPmllS2psHxGtbNHLqrjH7TkRRirnsqlhfUuodd7etL0AWpJpnPEzInsGdqP2H3_6uDhTdo5XQ2GXmDIfMwMy2ie8uvOgroUfugpPfeIpx5HbtmchXzVR_qtwKk2YX3vOJaRG36khkt6QLai-XnZqfD3VqUwxBgmPmQH-hAnk-8tKNAWmBKEIelZpo1tn3hm6P7',
    points: 40,
    basePoints: 40,
    status: 'approved',
    onTime: true,
    timingLabel: 'Realizado às 21:10 (Limite: 21:30)',
    criteria: 'Estojo abastecido, livros da sexta-feira guardados e agenda assinada.',
    limitTime: '21:30',
    completedAt: '21:10',
    duration: '10 min',
    feedback: 'Estojo abastecido, livros da sexta-feira guardados.',
    hasPenalty: false,
    penaltyAmount: 0,
    proofPhotoUrl: 'https://picsum.photos/seed/backpack_school/800/600',
  },
];

export const INITIAL_REWARDS: RewardItem[] = [
  {
    id: 'reward-item-1',
    title: '1 hora extra de videogame',
    cost: 200,
    childId: 'lucas',
    childName: 'Lucas',
    icon: 'videogame_asset',
    status: 'pending',
    requestedAt: '17:40 hoje',
    description: 'Tempo de tela adicional no fim de semana ou após o dever concluído.',
  },
  {
    id: 'reward-item-2',
    title: 'Livro de colorir novo',
    cost: 250,
    childId: 'beatriz',
    childName: 'Beatriz',
    icon: 'palette',
    status: 'delivered',
    deliveredAt: 'Ontem às 19:30 pelo Pai Admin',
    description: 'Caderno especial com desenhos e giz de cera brilhante.',
  },
  {
    id: 'reward-item-3',
    title: 'Passeio no parque de bicicleta',
    cost: 180,
    childId: 'beatriz',
    childName: 'Beatriz',
    icon: 'directions_bike',
    status: 'pending',
    requestedAt: 'Hoje às 14:15',
    description: 'Tarde no parque com piquenique e circuito de bike com os pais.',
  },
  {
    id: 'reward-item-4',
    title: 'Escolher o jantar de sexta-feira',
    cost: 150,
    childId: 'lucas',
    childName: 'Lucas',
    icon: 'restaurant',
    status: 'available',
    description: 'Direito de decidir o cardápio da família na noite de sexta.',
  },
  {
    id: 'reward-item-5',
    title: 'Sessão de cinema com pipoca',
    cost: 350,
    childId: 'beatriz',
    childName: 'Beatriz',
    icon: 'movie',
    status: 'available',
    description: 'Ingresso para lançamento no cinema acompanhado de combo pipoca.',
  },
  {
    id: 'reward-item-6',
    title: 'Kit de Lego / Construção',
    cost: 500,
    childId: 'lucas',
    childName: 'Lucas',
    icon: 'extension',
    status: 'available',
    description: 'Set temático de montagem espacial ou mecânico.',
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    title: 'Lucas concluiu Lição de Matemática',
    message: 'Envio efetuado com 25 min de atraso tolerável.',
    time: 'Há 18 min',
    unread: true,
    type: 'routine',
  },
  {
    id: 'notif-2',
    title: 'Beatriz organizou a mochila',
    message: 'Tarefa pronta antes do horário limite (21:10).',
    time: 'Há 35 min',
    unread: true,
    type: 'routine',
  },
  {
    id: 'notif-3',
    title: 'Resgate Solicitado',
    message: 'Lucas solicitou "1 hora extra de videogame" (200 pts).',
    time: 'Hoje às 17:40',
    unread: true,
    type: 'reward',
  },
  {
    id: 'notif-4',
    title: 'Meta Semanal Atingida',
    message: 'Beatriz alcançou 96% de consistência nesta semana!',
    time: 'Ontem',
    unread: false,
    type: 'system',
  },
];

export const INITIAL_TRANSACTIONS: PointTransaction[] = [
  {
    id: 'tx-1',
    childId: 'lucas',
    childName: 'Lucas',
    date: 'Hoje, 19:42',
    title: 'Arrumar a cama e organizar o quarto',
    type: 'earned',
    points: 50,
    category: 'Organização',
  },
  {
    id: 'tx-2',
    childId: 'lucas',
    childName: 'Lucas',
    date: 'Hoje, 17:40',
    title: 'Solicitação: 1h extra de videogame',
    type: 'spent',
    points: 200,
    category: 'Recompensa',
  },
  {
    id: 'tx-3',
    childId: 'beatriz',
    childName: 'Beatriz',
    date: 'Hoje, 20:15',
    title: 'Escovar dentes e lavar o rosto',
    type: 'earned',
    points: 30,
    category: 'Higiene',
  },
  {
    id: 'tx-4',
    childId: 'beatriz',
    childName: 'Beatriz',
    date: 'Ontem, 19:30',
    title: 'Resgate: Livro de colorir novo',
    type: 'spent',
    points: 250,
    category: 'Recompensa',
  },
  {
    id: 'tx-5',
    childId: 'lucas',
    childName: 'Lucas',
    date: 'Ontem, 20:00',
    title: 'Leitura de 30 minutos',
    type: 'earned',
    points: 40,
    category: 'Estudos',
  },
];

export const PARENT_USER = {
  name: 'Pai Admin',
  role: 'Administrador da Família',
  email: 'luizaugustomarcondessilveira@gmail.com',
  avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB2TGE5sY4_u-YbRXf6A2TaD6vXq136zr8JtzsNUkXi3BgwybEGQyg2IhUO2yZF6x2m_UuhJiNlgznUrtzs7qsmSOpTBzXWxRnw6cR2-bD2vBxrPfXBhXVIEKJW2QGJS_a0mSXPZXX4KpYe_Tws4M1UHRv4lGSk5cyhBB0djXf5XtnW8a_8kBYfk1l0kvP9t0d91wLmm3FHO4j0IzzuLCf8vxYv0R0RqhKt9J4yfIQo8NR8Og4Gx5qU',
};

export const LOGO_URL = 'https://lh3.googleusercontent.com/aida-public/AB6AXuBqY9KVMpPbddmJxwwP0xrJVJ3EiHOacevgznbUD1a9XXWwiMdViOwCmz_icTd6KWOyL9GvcNNDQNDwGJlMghTuYoqGHKDvhDxNvZyw2VcprC1Os9oaa7sjPhDaIclKm1n66AZLwjre02-T15OXShi_Q93yEd-h1TLF1cLju4Zh7WAHUnTG0BDVjZThGiLqq1n6K7fJAV7GRoOg5I8gH0BEyGoNg1A2CeFXtRoBXTg67A3AZa24BAdf';
